FROM registry.cn-beijing.aliyuncs.com/zero-tools/pal-docker AS base

RUN curl -JL https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/download/1.3.0-Update-2/PalServer-Linux-Test-Patch-Update-2 --output PalServer-Linux-Test && rm ./Pal/Binaries/Linux/PalServer-Linux-Test && mv PalServer-Linux-Test ./Pal/Binaries/Linux/
